---
apiVersion: v2
name: opensearch-operator
version: "25.11.0-rc1"
appVersion: "25.11.0-rc1"
description: The Stackable Operator for OpenSearch
home: https://github.com/stackabletech/opensearch-operator
maintainers:
  - name: Stackable
    url: https://www.stackable.tech
